### PR TITLE
Render a full page with EJS template

### PR DESCRIPTION
**Pull request by baens**
I am up for comments on whether EJS templates are ok, or if I should find something else. Honestly they were the easiest one I found (and I looked at Jade, mustache, and handlebars).

### CODE REVIEW

**Comment by nobleach** [comment]
We currently use Handlebars. The only benefit I see over ejs is that handlebars support some logic right out of the box. `{{#if}}{{else}}{{/if}` How's that for consistency. One could argue that logic has no place in a view template. Regardless, you're really just looking for an insertion point, so I'm fine with whatever library you choose.

**Comment by baens** [comment]
I'll change it to handlebars so I can get familiar with that in our environment

**Comment by baens** [comment]
There we go, handlebars rendering.

**Comment by ghost** [comment]
:+1:

**Pull request merged**
